### ISSUE TITLE
Ovapi is not working with Hassio 6.1

### ISSUE THREAD

**Issue by digitall12** [Paul-dH/Home-Assisant-Sensor-OvApi#29]
Since version 6.1 of HA your script ovapi is not working anymore. Will there be a fix for?  Your script works like a charm!

**Comment by Paul-dH** [comment]
Hi @digitall12, can you explain what is happening? Are there any errors in the logs that can help?

I'm happy to help, but I'm afraid that I need a little more information :)

**Comment by digitall12** [comment]
Well , the entity is not available.  This is my config.yaml:

## Sensor providing Public Transport information from [OVapi](http://www.ovapi.nl) in Home Assistant

##![Alt text](https://github.com/IIIdefconIII/Home-Assisant-Sensor-OvApi/blob/master/preview.png?raw=true "Title")
############################################
##         Public Transport OVAPI         ##
############################################
###### SENSORS -----------------------------
###### BUS naar CS -----------------------------
sensor:
  - platform: ovapi
    name: Bus naar CS
    timing_point_code: 37222300
    line_filter: 391, 393, 394, 395
    show_future_departures: 4

###### BUS naar ZMC -----------------------------

  - platform: ovapi
    name: Bus_naar ZMC
    timing_point_code: 30008030     
    line_filter: 391, 393, 394, 395
    show_future_departures: 4
    
################################################

And in Lovelace is many showing: Entity is not available sensor.bus naar cs

**Comment by digitall12** [comment]
After deleting the old custom component files and replacing with the one on your site; It is working again!
