### ISSUE TITLE
Using template the departure 1-4 do not work

### ISSUE THREAD

**Issue by svh1985** [Paul-dH/Home-Assisant-Sensor-OvApi#9]
Hi,

I've added the sample code (no modifications) for Departure 1-4, but I get "Nog geen gegevens". The main sensor does show a departure time. Do you have any tips on how to solve this?

Thanks!

**Comment by MRvH88** [comment]
Had the same issue, for now I use the following template sensors.

I replaced the base ovapi sensor with metro_e_blijdorp_0 in my ui, as the ovapi was not displaying the delay in lovelace. metro_e_blijdorp_1 can be copied depending on how may times departures you like to display.


    - platform: template
      sensors:
        metro_e_blijdorp_0:
          friendly_name: Departure
          entity_id: sensor.metro_e_blijdorp
          icon_template: "{{ state_attr('sensor.metro_e_blijdorp','icon') }}"
          value_template: >
            {%- set departure = state_attr('sensor.metro_e_blijdorp','departure') if state_attr('sensor.metro_e_blijdorp','departure') is defined and is != 'unknown' else 'No Info' %}
            {%- set message = '+ ' + state_attr('sensor.metro_e_blijdorp','delay') + ' min'  if state_attr('sensor.metro_e_blijdorp','delay') | int > 0 and is != 'unknown' else '' %}
              {{departure}} {{message}}
        metro_e_blijdorp_1:
          friendly_name: Departure
          entity_id: sensor.metro_e_blijdorp
          icon_template: "{{ state_attr('sensor.metro_e_blijdorp','icon') }}"
          value_template: >
            {%- set i = 0 %}
            {%- set departure = state_attr('sensor.metro_e_blijdorp','departures' )[i] if state_attr('sensor.metro_e_blijdorp','departures')[i] is defined and is != 'unknown' else 'No Info' %}
              {{departure}}
        metro_e_blijdorp_2:
          friendly_name: Departure
          entity_id: sensor.metro_e_blijdorp
          icon_template: "{{ state_attr('sensor.metro_e_blijdorp','icon') }}"
          value_template: >
            {%- set i = 1 %}
            {%- set departure = state_attr('sensor.metro_e_blijdorp','departures' )[i] if state_attr('sensor.metro_e_blijdorp','departures')[i] is defined and is != 'unknown' else 'No Info' %}
              {{departure}}

**Comment by IIIdefconIII** [comment]
u can use show_future_departures: True, its still under develepment cause the name doesnt show vertrek. just the name of the sensor itself.

sensor:
  - platform: ovapi
    name: Tram 23
    timing_point_code: 'xxx'
    show_future_departures: True

**Comment by IIIdefconIII** [comment]
just found that its already fixed in PR #7

**Comment by Paul-dH** [comment]
Please see the comment of: @IIIdefconIII
